### ISSUE TITLE
The new version is not published

### ISSUE THREAD

**Issue by cdarken** [gowravshekar/font-awesome-webpack#31]
The new tag is not instalable, may be because you forgot to update the version in package.json (I'm not exactly sure this is now npmjs works) ? I had to install from the master branch in my project.

**Comment by wolfadex** [comment]
I'm not sure if npm pulls from github automatically. Assuming it doesn't we'll have to wait for @gowravshekar to publish to npm.

**Comment by amyrhsieh** [comment]
Please publish to npm soon. I have a project that is waiting on the new version of this, so that we can upgrade to Webpack 2. Everything else in our Webpack 2 upgrade works besides this package, and I know this new version will work with our upgrade because I tried manually copying it into node_modules. It would be great if we could just increment the version in package.json. Thanks.

**Comment by cdarken** [comment]
@amyrhsieh for a quick build you can update your `package.json` and specify `git+https://github.com/gowravshekar/font-awesome-webpack#master` instead of the version, until the new version is published.

**Comment by cdarken** [comment]
@wolfadex I saw that you changed the version in the package.json file, but you didn't tagged it. On npmjs the version is worded like this: "0.0.4 is the latest of 4 releases". There are 4 tags here on github. Maybe if you update the version to beta.2 and also tag it npmjs will fetch the new version.

**Comment by wolfadex** [comment]
@cdarken I've added another release with 0.0.5-beta.2 in both package.json and as the tag.

**Comment by amyrhsieh** [comment]
It seems to me that in order to publish to npm, the owner @gowravshekar must be the one to run `npm install`, but it seems they have been inactive for some time, unfortunately.

For my own project, I have removed this package, but kept the loaders as described in the README. I am now using `font-awesome` package instead: https://www.npmjs.com/package/font-awesome
And instead of: `require("font-awesome-webpack");`
I do : `require('font-awesome/css/font-awesome.min.css');`
This is working for me.

An alternative approach might be if somebody wants to fork this repo and take ownership, then they should be able to publish to npm.

**Comment by wolfadex** [comment]
@amyrhsieh there is font-aweomse-webpack2 I know. I was able to get @gowravshekar to add me to this project, but only on github so I don't have access to the npm repo. I did email them, about 1 week ago, to see if I can get access to npm too but they've yet to respond.

**Comment by amyrhsieh** [comment]
I tried the font-awesome-webpack2 fork, but it was forked longer ago and doesn't seem compatible with webpack2, from my brief attempt.  That's unfortunate they didn't get back to you. Thank you for your efforts and prompt response!

**Comment by cdarken** [comment]
@wolfadex yeah, after a bit more research it seems like you need to do `npm publish`.
@amyrhsieh did you try adding the repo as I said above? it works just fine for me, just upgraded with `yarn upgrade`, the version is the latest from the repo.

**Comment by wolfadex** [comment]
@cdarken @amyrhsieh I have access to npm now, I'll try to publish 0.0.5 tomorrow.

**Comment by wolfadex** [comment]
New version is published
